### ISSUE TITLE
Responsible vulnerability disclosure 

### ISSUE THREAD

**Issue by Sim4n6** [ewen-lbh/ffcss#74]
Hi,

I may have identified a low-severity vulnerability in ewen-lbh/ffcss codebase. Please consider enabling the GitHub private vulnerability reporting so the process can go smoothly...

Thank you in advance

 - https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by ewen-lbh** [comment]
Done! I just saw this, sorry for the (ridiculous) delay

**Comment by Sim4n6** [comment]
Report submitted. thanks
